@startuml
' Classes

package FrontEnd {
    class WebPresentation
}

package "Application"{

    package Rezepte{
        class useCases{
            createRezept()
            readRezept()
            updateRezept()
            deleteRezept()
            createZutat()
            readZutat()
            updateZutat()
            deleteZutat()
        }
    }

    package "Filter"{
        class TheBigFilter
    }
    package "BorderClasses"{
        class BorderRezept
        class BorderAnleitung
        class BorderZutat
    }
}

package "Data"{
    package "Entity"{

        class Rezept{
            anleitung Anleitung
            schritte []string
        }

        class Zutat{
            name string
            menge string
            tag string
        }
    }

    package "CRUD"{
        class CRUDRezept{
        }
    }

    package "Queries"{
        class Queries
    }
}

'Relations
Rezept ..|> Zutat

CRUDRezept ..|> Rezept

TheBigFilter ..|> CRUDRezept

BorderZutat ..|> TheBigFilter
BorderRezept ..|> TheBigFilter
BorderAnleitung ..|> TheBigFilter

useCases ..|> BorderZutat
useCases ..|> BorderRezept
useCases ..|> BorderAnleitung

WebPresentation ..|> useCases

@enduml