version: '3.7'

services:
  db:
      image: mysql:latest
      volumes:
        - db_data:/var/lib/mysql
      restart: always
      ports:
        - "3306:3306"
      environment:
        MYSQL_ROOT_PASSWORD: king
        MYSQL_DATABASE: rezepte
        MYSQL_USER: user
        MYSQL_PASSWORD: user

volumes:
  db_data: {}
