version: '3.3'

services:
  db:
      image: mysql:latest
      volumes:
        - db_data:/var/lib/mysql
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: king
        MYSQL_DATABASE: webalayzer
        MYSQL_USER: user
        MYSQL_PASSWORD: user

volumes:
  db_data: {}
